# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 19:25
from __future__ import unicode_literals

import bigbrother_sniper.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_checker', models.BooleanField(default=False)),
                ('check_time', models.DateTimeField(editable=False, null=True)),
                ('check_start_time', models.DateTimeField(null=True)),
                ('is_late_checker', models.BooleanField(default=False)),
                ('is_reasonableabsent_checker', models.BooleanField(default=False)),
                ('is_absent_checker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
                ('activate_absence', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('absence_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=256)),
                ('lecture_num', models.CharField(default=b'', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LectureReceiveCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LectureUuidRecord',
            fields=[
                ('time_difference', models.BooleanField(default=True)),
                ('time_difference_check_flag', models.BooleanField(default=False)),
                ('reachLimiter', models.CharField(default=4, max_length=2)),
                ('default_uuid', models.CharField(default=b'4a4ece607eb011e', max_length=15)),
                ('lecture_num', models.CharField(default=b'', max_length=6, primary_key=True, serialize=False)),
                ('prime_num', models.CharField(default=99991, max_length=10)),
                ('secret_key', models.CharField(default=54321, max_length=10)),
                ('init_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('uuid_now', models.CharField(default=b'', max_length=32)),
                ('uuid_pre', models.CharField(default=b'', max_length=32)),
                ('uuid_next', models.CharField(default=b'', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('absence_time_set', models.CharField(default=30, max_length=2)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bigbrother_sniper.models.ImageUploadNameBind)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('Crypt_rand_N', models.CharField(default=b'', max_length=6)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecturereceivecard',
            name='card_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.StudentProfile'),
        ),
        migrations.AddField(
            model_name='lecturereceivecard',
            name='target_lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.Lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.ProfessorProfile'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.Lecture'),
        ),
        migrations.AddField(
            model_name='attendancecard',
            name='checker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.StudentProfile'),
        ),
        migrations.AddField(
            model_name='attendancecard',
            name='record_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbrother_sniper.AttendanceRecord'),
        ),
    ]
