# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbrother_sniper', '0002_labelguardlist_textguardlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAlertMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=6)),
                ('drop_on_flag', models.BooleanField(default=False)),
                ('keyword', models.CharField(max_length=36)),
            ],
        ),
    ]
