# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbrother_sniper', '0003_postalertmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelguardlist',
            name='explain',
            field=models.CharField(default=b'', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='textguardlist',
            name='explain',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='labelguardlist',
            name='label_value',
            field=models.CharField(default=b'', max_length=32),
        ),
        migrations.AlterField(
            model_name='postalertmessagelog',
            name='keyword',
            field=models.CharField(default=b'', max_length=36),
        ),
        migrations.AlterField(
            model_name='postalertmessagelog',
            name='username',
            field=models.CharField(default=b'', max_length=6),
        ),
        migrations.AlterField(
            model_name='textguardlist',
            name='text_value',
            field=models.CharField(default=b'', max_length=32),
        ),
    ]
