# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbrother_sniper', '0004_auto_20180317_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalertmessagelog',
            name='pictureBase64',
            field=models.CharField(default=b'', max_length=1024),
        ),
    ]
