# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigbrother_sniper', '0005_postalertmessagelog_picturebase64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancecard',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='attendancecard',
            name='record_to',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lecturereceivecard',
            name='card_owner',
        ),
        migrations.RemoveField(
            model_name='lecturereceivecard',
            name='target_lecture',
        ),
        migrations.DeleteModel(
            name='LectureUuidRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceCard',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='LectureReceiveCard',
        ),
    ]
